services:

  libreria_db:
    image: postgres:15
    container_name: libreria_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: libreria_db
      POSTGRES_USER: libreria_user
      POSTGRES_PASSWORD: libreria_pass
    ports:
      - "5434:5432"       # Puerto 5434 en el host → 5432 dentro del contenedor
    volumes:
      - libreria_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U libreria_user -d libreria_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  libreria_pgdata:
    driver: local
